# frozen_string_literal: true

module ZoqlConsole
  class Completor
    ZUORA_OBJECTS = %w[
      Account
      AccountingCode
      AccountingPeriod
      Amendment
      ApplicationGroup
      BillingRun
      Contact
      ContactSnapshot
      CreditBalanceAdjustment
      CreditMemo
      CreditMemoApplication
      CreditMemoApplicationItem
      CreditMemoItem
      CreditMemoPart
      CreditMemoPartItem
      CreditTaxationItem
      FXCustomRate
      DebitMemo
      DebitMemoItem
      DebitTaxationItem
      DiscountAppliedMetrics
      Tenant
      PaymentGatewayReconciliationEventLog
      PaymentReconciliationJob
      PaymentReconciliationLog
      Invoice
      InvoiceAdjustment
      InvoiceItem
      InvoiceItemAdjustment
      InvoicePayment
      JournalEntry
      JournalEntryItem
      JournalRun
      Order
      OrderAction
      OrderElp
      OrderItem
      OrderMrr
      OrderQuantity
      OrderTcb
      OrderTcv
      Payment
      PaymentApplication
      PaymentApplicationItem
      PaymentMethod
      PaymentMethodSnapshot
      PaymentMethodTransactionLog
      UpdaterDetail
      PaymentPart
      PaymentPartItem
      PaymentRun
      PaymentTransactionLog
      ProcessedUsage
      Product
      ProductRatePlan
      ProductRatePlanCharge
      ProductRatePlanChargeTier
      RatePlan
      RatePlanCharge
      RatePlanChargeTier
      Refund
      RefundApplication
      RefundApplicationItem
      RefundInvoicePayment
      RefundPart
      RefundPartItem
      RefundTransactionLog
      RevenueChargeSummary
      RevenueChargeSummaryItem
      RevenueEvent
      RevenueEventCreditMemoItem
      RevenueEventDebitMemoItem
      RevenueEventInvoiceItem
      RevenueEventInvoiceItemAdjustment
      RevenueEventItem
      RevenueEventItemCreditMemoItem
      RevenueEventItemDebitMemoItem
      RevenueEventItemInvoiceItem
      RevenueEventItemInvoiceItemAdjustment
      RevenueEventType
      RevenueSchedule
      RevenueScheduleCreditMemoItem
      RevenueScheduleDebitMemoItem
      RevenueScheduleInvoiceItem
      RevenueScheduleInvoiceItemAdjustment
      RevenueScheduleItem
      RevenueScheduleItemCreditMemoItem
      RevenueScheduleItemDebitMemoItem
      RevenueScheduleItemInvoiceItem
      RevenueScheduleItemInvoiceItemAdjustment
      Subscription
      TaxableItemSnapshot
      TaxationItem
      UpdaterBatch
      Usage
    ].freeze
  end
end
